### ISSUE TITLE
Script fails with wrong argument keyword

### ISSUE THREAD

**Issue by keamy** [florianbeer/grafana-netatmo#10]
Method lastData no longer accepts argument station starting lnetatmo version 2 see the [release](https://github.com/philippelt/netatmo-api-python/compare/1.6.2...2.0.0)

```
Traceback (most recent call last):
  File "./netatmotest.py", line 36, in <module>
    for module, moduleData in weatherData.lastData(station=station_name, exclude=3600).items():
TypeError: lastData() got an unexpected keyword argument 'station'
```

**Comment by aheinhold** [comment]
Hello,

i have the same problem. Can you please fix it?

```
Traceback (most recent call last):
  File "/usr/local/bin/netatmo_influx.py", line 37, in <module>
    for module, moduleData in weatherData.lastData(station=station_name, exclude=3600).items():
TypeError: lastData() got an unexpected keyword argument 'station'
```

Regards,
Alex

**Comment by karaktaka** [comment]
Hey, I don't know if he will ever merge anything as this project seems dead, but if you like, I fixed this some time ago in my fork.
https://github.com/karaktaka/grafana-netatmo

**Comment by sweh** [comment]
This should fix the error: 
```           
            …
            weatherData.default_station_data = weatherData.stationByName(station_name)
            for module, moduleData in weatherData.lastData(exclude=3600).items():
                …
```

**Comment by florianbeer** [comment]
This was fixed in the upstream library: https://github.com/philippelt/netatmo-api-python/issues/50
