### ISSUE TITLE
Error with netatmo authentification

### ISSUE THREAD

**Issue by catalincolesnicov** [florianbeer/grafana-netatmo#22]
Hello,
since some days i get following error running the script.

```
code=400, reason=, body=b'{"error":"invalid_grant"}'
Traceback (most recent call last):
  File "/usr/local/bin/netatmo_influx.py", line 9, in <module>
    weatherData = lnetatmo.WeatherStationData(authorization)
  File "/usr/local/lib/python3.9/dist-packages/lnetatmo.py", line 413, in __init__
    self.getAuthToken = authData.accessToken
  File "/usr/local/lib/python3.9/dist-packages/lnetatmo.py", line 240, in accessToken
    if self.expiration < time.time() : self.renew_token()
  File "/usr/local/lib/python3.9/dist-packages/lnetatmo.py", line 251, in renew_token
    if self.refreshToken != resp['refresh_token']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by psykok** [comment]
I'm getting the same error.
Apparently the API token is expiring each time you active it.
The authentication procedure has been changed again by Netatmo.

**Comment by webbrain-one** [comment]
Hi, thanks for reporting this! I’ve opened [PR #24](https://github.com/florianbeer/grafana-netatmo/pull/24) to fix the Netatmo authentication issue. It handles the token renewal flow more robustly so the script doesn’t crash with `invalid_grant` / `NoneType` when the refresh token response is missing. Let me know if it works for you!
